// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_BooleanList_H__
#define TYPY_BooleanList_H__

#include "typy.h"



TypyHeaderBegin(BooleanList);
	List< bool >* p_bl;
TypyHeaderEnd(BooleanList);

#endif // TYPY_BooleanList_H__
