// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#include "BooleanList.h"
#include "list.h"
#include "dict.h"

TypyObjectBegin(BooleanList);

BooleanList::BooleanList() : Message() {
	ZERO(BooleanList, p_bl, _cached_size);
}

void BooleanList::Clear() {
	::typy::Clear(p_bl);
}

int BooleanList::Visit(visitproc visit, void* arg) {
	register int result = 0;
	if((result = ::typy::Visit(p_bl, visit, arg)) != 0) { return result; }
	return result;
}

void BooleanList::MergeFrom(const BooleanList& from) {
	if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
	::typy::MergeFrom(p_bl, from.p_bl);
}

void BooleanList::SerializeWithCachedSizes(CodedOutputStream* output) const {
	::typy::Write(1, p_bl, output);
}

int BooleanList::ByteSize() const {
	int total_size = 0;
	::typy::ByteSize(total_size, 1, p_bl);
	GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
	_cached_size = total_size;
	GOOGLE_SAFE_CONCURRENT_WRITES_END();
	return total_size;
}

bool BooleanList::MergePartialFromCodedStream(CodedInputStream* input) {
	BEGINE_READ_CASE(1)
	FIRST_READ_REPEATED_PRIMITIVE_CASE(1, p_bl, bool)
	END_READ_CASE()
}

PyObject* BooleanList::Json(bool slim) {
	PyObject* json = PyDict_New();
	if (json == NULL) { return NULL; }
	PyObject* value = PyString_FromString(BooleanList::Name);
	if (value == NULL) { Py_DECREF(json); return NULL; }
	PyDict_SetItemString(json, "_t", value);
	Py_DECREF(value);
	value = ::typy::Json(p_bl, slim);
	if (value != NULL) { PyDict_SetItemString(json, "bl", value); Py_DECREF(value); }
	return json;
}

BooleanList* BooleanList::FromJson(PyObject* json) {
	if (!PyObject_HasAttrString(json, "iteritems")) {
		FormatTypeError(json, "FromJson expect dict, but ");
		return NULL;
	}
	PyObject* value = PyObject_GetItem(json, ScopedPyObjectPtr(PyString_FromString("_t")).get());
	if (value == NULL) {
		FormatTypeError(json, "Json expect _t, ");
		return NULL;
	} else if (PyUnicode_Check(value)) {
		PyObject* _value = PyUnicode_AsEncodedObject(value, "utf-8", NULL);
		Py_DECREF(value);
		value = _value;
	} else if (!PyBytes_Check(value)) {
		FormatTypeError(value, "Json _t expect String, but ");
		return NULL;
	}
	if (strcmp(PyBytes_AS_STRING(value), BooleanList::Name)) {
		PyErr_Format(PyExc_TypeError, "Object expect '%.100s', but Json has type %.100s",
			BooleanList::Name, PyBytes_AS_STRING(value));
		Py_DECREF(value);
		return NULL;
	}
	PyErr_Clear();
	Py_DECREF(value);
	BooleanList* object = new BooleanList();
	value = PyObject_GetItem(json, ScopedPyObjectPtr(PyString_FromString("bl")).get()); PyErr_Clear();
	if (value != NULL) { if (!::typy::FromJson(object->p_bl, value)) { Py_DECREF(value); return NULL; } Py_DECREF(value); }
	return object;
}

// ===================================================================

const int BooleanList::PropertyCount = 1;
char* BooleanList::Properties[] = {
	"bl"
};

int BooleanList::PropertyByteSize(int tag) const {
	int size = 0;
	switch(tag) {
	case 1: ::typy::ByteSize(size, 1, p_bl); if (size == 0) { size = 1; } break;
	}
	return size;
}

void BooleanList::SerializeProperty(CodedOutputStream* output, int tag) const {
	switch(tag) {
	case 1:
		::typy::Write(1, p_bl, output);
		if (output->ByteCount() <= 0) {
			::typy::WriteTag(1, p_bl, output);
		}
		break;
	}
}

int BooleanList::DeserializeProperty(CodedInputStream* input) {
	const void* data;
	int size;
	input->GetDirectBufferPointerInline(&data, &size);
	CodedInputStream tagInput(reinterpret_cast<const uint8*>(data), size);
	::std::pair<uint32, bool> p = tagInput.ReadTagWithCutoff(_MAXTAG(25)
		<= 0x7F ? 0x7F : (_MAXTAG(25) <= 0x3FFF ? 0x3FFF : _MAXTAG(25)));
	uint32 tag = p.first;
	if (!p.second) { return 0; }

	int index = WireFormatLite::GetTagFieldNumber(tag);
	switch(index) {
	case 1: ::typy::Clear(p_bl); break;
	}

	if (!tagInput.ExpectAtEnd()) {
		MergePartialFromCodedStream(input);
	}
	return index;
}

bool BooleanList::SetPropertySequence(PyObject* args) {
	for (Py_ssize_t i = 0; i < PyTuple_GET_SIZE(args); i++) {
		switch(i) {
		case 0: if (!::typy::CheckAndSet(PyTuple_GET_ITEM(args, 0), p_bl, "Property 'bl' expect List(bool), but ")) { return false; } break;
		default: PyErr_Format(PyExc_TypeError, "Unsurported property number %lu.", i); return false;
		}
	}
	return true;
}

PyObject* BooleanList::GetPropertySequence() {
	PyObject* result = PyTuple_New(1);
	if (result == NULL) { return result; }
	PyTuple_SET_ITEM(result, 0, ::typy::GetPyObject(p_bl));
	return result;
}

// ===================================================================

TYPY_GETSET(BooleanList, p_bl, List(bool));

template <> PyGetSetDef Object<BooleanList>::GetSet[] = {
	{"bl", (getter)Get_p_bl, (setter)Set_p_bl, "Property bl"},
	{NULL}
};

TypyObjectEnd(BooleanList);
