// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_onInitRuntime_H__
#define TYPY_onInitRuntime_H__

#include "typy.h"

#include "SkillParam.h"

TypyHeaderBegin(onInitRuntime);
	bytes p_buckID;
	List< int32 >* p_events;
	int32 p_flowID;
	bytes p_ownerID;
	List< SkillParam >* p_params;
	List< int32 >* p_passBuckEvents;
	int32 p_prev;
	int32 p_skillID;
	int32 p_skillIdx;
	SINGLE_ARG(Dict<bytes, List< int32 > >)* p_specificEvents;
	int32 p_uiid;
	int32 p_unitIndex;
TypyHeaderEnd(onInitRuntime);

#endif // TYPY_onInitRuntime_H__
