// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_playSoundVO_2_H__
#define TYPY_playSoundVO_2_H__

#include "typy.h"



TypyHeaderBegin(playSoundVO_2);
	string p_path;
TypyHeaderEnd(playSoundVO_2);

#endif // TYPY_playSoundVO_2_H__
