// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_playSoundVO_1_H__
#define TYPY_playSoundVO_1_H__

#include "typy.h"



TypyHeaderBegin(playSoundVO_1);
	float p_interval;
	string p_path;
TypyHeaderEnd(playSoundVO_1);

#endif // TYPY_playSoundVO_1_H__
