// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_PYTHON_PyType_H__
#define TYPY_PYTHON_PyType_H__

#include "typy.h"

namespace typy {

struct Shadow_PyType{};

} // namespace typy
#endif // TYPY_PYTHON_PyType_H__
