// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_RPG_H__
#define TYPY_RPG_H__

#include "typy.h"

#include "Fighter.h"

TypyHeaderBegin(RPG);
	Fighter* p_fighter;
TypyHeaderEnd(RPG);

#endif // TYPY_RPG_H__
