// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_SkillParam_H__
#define TYPY_SkillParam_H__

#include "typy.h"

#include "Vbbyfi.h"
#include "Vector3.h"

TypyHeaderBegin(SkillParam);
	bytes p_buckID;
	Python<Shadow_Vector3>* p_destPos;
	Python<Shadow_Vector3>* p_destRot;
	SINGLE_ARG(Dict<bytes, Vbbyfi >)* p_extraParam;
	Python<Shadow_Vector3>* p_origPos;
	Python<Shadow_Vector3>* p_origRot;
	bytes p_targetID;
	List< bytes >* p_targetIDs;
TypyHeaderEnd(SkillParam);

#endif // TYPY_SkillParam_H__
