// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_Vbbyfi_H__
#define TYPY_Vbbyfi_H__

#include "typy.h"



TypyVariantHeader(Vbbyfi, SINGLE_ARG(
	bool _value1;
	bytes _value2;
	float _value3;
	int32 _value4;
));

#endif // TYPY_Vbbyfi_H__
