// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_VbyfiVector2_H__
#define TYPY_VbyfiVector2_H__

#include "typy.h"

#include "Vector2.h"

TypyVariantHeader(VbyfiVector2, SINGLE_ARG(
	bytes _value1;
	float _value2;
	int32 _value3;
	Vector2* _value4;
));

#endif // TYPY_VbyfiVector2_H__
