// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_PYTHON_Vector3_H__
#define TYPY_PYTHON_Vector3_H__

#include "typy.h"

namespace typy {

struct Shadow_Vector3{};

} // namespace typy
#endif // TYPY_PYTHON_Vector3_H__
