// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_VfisVector2_H__
#define TYPY_VfisVector2_H__

#include "typy.h"

#include "Vector2.h"

TypyVariantHeader(VfisVector2, SINGLE_ARG(
	float _value1;
	int32 _value2;
	string _value3;
	Vector2* _value4;
));

#endif // TYPY_VfisVector2_H__
