// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_Vfs_H__
#define TYPY_Vfs_H__

#include "typy.h"



TypyVariantHeader(Vfs, SINGLE_ARG(
	float _value1;
	string _value2;
));

#endif // TYPY_Vfs_H__
