// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_Vi7dD6BPRQE1LZ8XQj04V6Mg_H__
#define TYPY_Vi7dD6BPRQE1LZ8XQj04V6Mg_H__

#include "typy.h"

#include "Vfs.h"

TypyVariantHeader(Vi7dD6BPRQE1LZ8XQj04V6Mg, SINGLE_ARG(
	int32 _value1;
	List< Vfs >* _value2;
));

#endif // TYPY_Vi7dD6BPRQE1LZ8XQj04V6Mg_H__
