// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_Vi__zxiaLfTra898A6_6whFCg_H__
#define TYPY_Vi__zxiaLfTra898A6_6whFCg_H__

#include "typy.h"

#include "Vfs.h"

TypyVariantHeader(Vi__zxiaLfTra898A6_6whFCg, SINGLE_ARG(
	SINGLE_ARG(Dict<int32, Vfs >)* _value1;
	int32 _value2;
));

#endif // TYPY_Vi__zxiaLfTra898A6_6whFCg_H__
