// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_ViDiVfs_H__
#define TYPY_ViDiVfs_H__

#include "typy.h"

#include "Vfs.h"

TypyVariantHeader(ViDiVfs, SINGLE_ARG(
	SINGLE_ARG(Dict<int32, Vfs >)* _value1;
	int32 _value2;
));

#endif // TYPY_ViDiVfs_H__
