// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_ViDif_H__
#define TYPY_ViDif_H__

#include "typy.h"



TypyVariantHeader(ViDif, SINGLE_ARG(
	SINGLE_ARG(Dict<int32, float >)* _value1;
	int32 _value2;
));

#endif // TYPY_ViDif_H__
