// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_ViLf_H__
#define TYPY_ViLf_H__

#include "typy.h"



TypyVariantHeader(ViLf, SINGLE_ARG(
	int32 _value1;
	List< float >* _value2;
));

#endif // TYPY_ViLf_H__
