// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_ViLVfs_H__
#define TYPY_ViLVfs_H__

#include "typy.h"

#include "Vfs.h"

TypyVariantHeader(ViLVfs, SINGLE_ARG(
	int32 _value1;
	List< Vfs >* _value2;
));

#endif // TYPY_ViLVfs_H__
