// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_ViSlI3tNgu2aFVB8BXYUxf9w_H__
#define TYPY_ViSlI3tNgu2aFVB8BXYUxf9w_H__

#include "typy.h"

#include "Vfs.h"

TypyVariantHeader(ViSlI3tNgu2aFVB8BXYUxf9w, SINGLE_ARG(
	int32 _value1;
	List< Vfs >* _value2;
));

#endif // TYPY_ViSlI3tNgu2aFVB8BXYUxf9w_H__
