// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_VLf_H__
#define TYPY_VLf_H__

#include "typy.h"



TypyVariantHeader(VLf, SINGLE_ARG(
	List< float >* _value1;
));

#endif // TYPY_VLf_H__
