// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_VLVector2_H__
#define TYPY_VLVector2_H__

#include "typy.h"

#include "Vector2.h"

TypyVariantHeader(VLVector2, SINGLE_ARG(
	List< Vector2 >* _value1;
));

#endif // TYPY_VLVector2_H__
