// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_Vq0t2631Zu6lArqg9rFtFlQ_H__
#define TYPY_Vq0t2631Zu6lArqg9rFtFlQ_H__

#include "typy.h"



TypyVariantHeader(Vq0t2631Zu6lArqg9rFtFlQ, SINGLE_ARG(
	int32 _value1;
	List< float >* _value2;
));

#endif // TYPY_Vq0t2631Zu6lArqg9rFtFlQ_H__
