// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#include "VQYZcwhNx5__EgIiJ__uNsYGw.h"
#include "list.h"
#include "dict.h"

TypyVariantBegin(VQYZcwhNx5__EgIiJ__uNsYGw);

void VQYZcwhNx5__EgIiJ__uNsYGw::Clear() {
	switch (_tag) {
	case 1: ::typy::Clear(_value1); break;
	}
	_tag = 0;
}

void VQYZcwhNx5__EgIiJ__uNsYGw::CopyFrom(const VQYZcwhNx5__EgIiJ__uNsYGw& from) {
	if (&from == this) { return; }
	if (_tag != 0 && _tag != from._tag) { Clear(); }
	switch (from._tag) {
	case 1: ::typy::CopyFrom(_value1, from._value1); break;
	}
	_tag = from._tag;
}

void VQYZcwhNx5__EgIiJ__uNsYGw::MergeFrom(const VQYZcwhNx5__EgIiJ__uNsYGw& from) {
	if (GOOGLE_PREDICT_FALSE(&from == this)) {
		GOOGLE_CHECK(false) << __FILE__ << ":" << __LINE__;
	}
	if (from._tag == 0) { return; }
	if (_tag != 0 && _tag != from._tag) { Clear(); }
	switch (from._tag) {
	case 1: ::typy::MergeFrom(_value1, from._value1); break;
	}
	_tag = from._tag;
}

void VQYZcwhNx5__EgIiJ__uNsYGw::SerializeWithCachedSizes(CodedOutputStream* output) const {
	switch (_tag) {
	case 1: ::typy::Write(_tag, _value1, output); break;
	}
}

int VQYZcwhNx5__EgIiJ__uNsYGw::ByteSize() const {
	int total_size = 0;
	switch (_tag) {
	case 1: ::typy::ByteSize(total_size, 1, _value1); break;
	}
	GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
	_cached_size = total_size;
	GOOGLE_SAFE_CONCURRENT_WRITES_END();
	return total_size;
}

bool VQYZcwhNx5__EgIiJ__uNsYGw::MergePartialFromCodedStream(CodedInputStream* input) {
	BEGINE_READ_CASE(1)
	FIRST_READ_VARIANT_CASE(1, _value1, List< float >)
	END_READ_CASE()
}

PyObject* VQYZcwhNx5__EgIiJ__uNsYGw::toPyObject() {
	switch (_tag) {
	case 1: return ::typy::GetPyObject(_value1);
	default: Py_RETURN_NONE;
	}
}

bool VQYZcwhNx5__EgIiJ__uNsYGw::fromPyObject(PyObject* value) {
	if (PyObject_TypeCheck(value, &List< float >::_Type) || PySequence_Check(value)) {
		if (_tag != 0 && _tag != 1) { Clear(); }
		if (::typy::CheckAndSet(value, _value1, "List of Variant expect List(float), but ")) {
			_tag = 1;
			return true;
		}
		return false;
	}
	return false;
}

bool CheckAndSet(PyObject* arg, VQYZcwhNx5__EgIiJ__uNsYGw*& value, const char* err) {
	if (arg == Py_None) {
		delete value; value = NULL;
		return true;
	}
	if (value == NULL) {
		value = new VQYZcwhNx5__EgIiJ__uNsYGw;
	}
	if (!value->fromPyObject(arg)) {
		delete value; value = NULL;
		FormatTypeError(arg, err);
		return false;
	}
	return true;
}

TypyVariantEnd(VQYZcwhNx5__EgIiJ__uNsYGw);
