// Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

#ifndef TYPY_VQYZcwhNx5__EgIiJ__uNsYGw_H__
#define TYPY_VQYZcwhNx5__EgIiJ__uNsYGw_H__

#include "typy.h"



TypyVariantHeader(VQYZcwhNx5__EgIiJ__uNsYGw, SINGLE_ARG(
	List< float >* _value1;
));

#endif // TYPY_VQYZcwhNx5__EgIiJ__uNsYGw_H__
