#-*- coding: utf-8 -*-
# Copyright 2017 ibelie, Chen Jie, Joungtao. All rights reserved.
# Use of this source code is governed by The MIT License
# that can be found in the LICENSE file.

def GenerateDescriptor(_typyDir = None):
	import os
	import codecs
	if _typyDir is None:
		_typyDir = os.path.dirname(__file__)
	path = os.path.abspath(_typyDir) + '/_typy.py'

	with codecs.open(path, 'w', 'utf-8') as f:
		f.write(TYPY_PY__)

TYPY_PY__ = ur"""#-*- coding: utf-8 -*-
# Generated by the typy Cpp.GenerateExtention.  DO NOT EDIT!

import _typyd
setDefaultEncodingUTF8 = _typyd.setDefaultEncodingUTF8

"""
